<?php

namespace Toast\News;


use Toast\News\Blog;
use Toast\News\News;
use Toast\News\Article;
use SilverStripe\Dev\Debug;
use Toast\Pages\GuestHolderPage;
use SilverStripe\Forms\FieldList;
use SilverStripe\Control\Director;
use SilverStripe\ORM\DataExtension;
use SilverStripe\Control\Controller;

class TaxonomyTypeExtension extends DataExtension
{
    private static $db = [
        'Title' => 'Varchar'
    ];
    private static $belongs_many_many = [
        'News' => News::class,
        'GuestPages' => GuestHolderPage::class,
    ];

    public function updateCMSFields(FieldList $fields)
    {
        parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
        $fields->removeByName(['Name', 'News', 'GuestPages']);
    }

    private static $summary_fields = array(
        'Title' => 'Title'
    );

}